env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:jest/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  warnOnUnsupportedTypeScriptVersion: true
plugins:
  - '@typescript-eslint'
  - 'jest'
  - 'react'
rules:
  '@typescript-eslint/no-inferrable-types': 0
  arrow-body-style:
    - error
    - as-needed
  arrow-spacing: error
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
    - always
  indent: 
    - error
    - 2
    - SwitchCase: 1
  key-spacing: error
  keyword-spacing: error
  max-len:
    - error
    - 100
  max-lines:
    - error
    - 200
  no-trailing-spaces: error
  prefer-const: error
  quotes:
    - error
    - single
  semi:
    - error
    - always
settings:
  react:
    version: detect
root: true