name: Tag

on:
  push:
    tags:
      - 'v*.*.*'


jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest

    env:
      SKIP_PREFLIGHT_CHECK: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: git config user.name "gh" && git config user.email "gh@github.com"
      - run: npm run deploy
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
